# Generated by Django 4.1.3 on 2022-12-26 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="doctor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="base.doctor",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="base.patient",
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="address",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="phone",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="patient",
            name="address",
            field=models.CharField(max_length=200),
        ),
    ]
