# Generated by Django 4.1.3 on 2022-12-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_appointment_doctor_alter_appointment_patient_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="address",
            field=models.CharField(max_length=200),
        ),
    ]
