# Generated by Django 4.1.3 on 2022-12-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_doctor_address"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="doctor",
            options={"ordering": ["-created", "-updated"]},
        ),
        migrations.AlterField(
            model_name="appointment",
            name="date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="time",
            field=models.TimeField(auto_now_add=True),
        ),
    ]
