# Generated by Django 4.1.3 on 2022-12-29 10:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_doctor_options_alter_appointment_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appointment",
            options={"ordering": ["-updated", "-created"]},
        ),
        migrations.AddField(
            model_name="appointment",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appointment",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="time",
            field=models.TimeField(),
        ),
    ]
