# Generated by Django 4.1.3 on 2022-12-29 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_alter_appointment_options_appointment_created_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointment",
            old_name="doctor",
            new_name="Doctor",
        ),
        migrations.RenameField(
            model_name="appointment",
            old_name="patient",
            new_name="Patient",
        ),
    ]
