# Generated by Django 4.1.3 on 2022-12-29 17:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_rename_doctor_appointment_doctor_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appointment",
            options={"ordering": ["-created", "-updated"]},
        ),
        migrations.AlterModelOptions(
            name="patient",
            options={"ordering": ["-created", "-updated"]},
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="Doctor",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="Patient",
        ),
        migrations.AddField(
            model_name="patient",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patient",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="doctor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="base.doctor",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="base.patient",
            ),
        ),
    ]
